7, 7, 66, 26
Kingdoms Report
Click on this scroll or press F1 to bring up the Kingdoms Report. Click on it again or press ESC to close it.
~
66, 6, 128, 24
Villages Report
Click on this scroll or press F2 to bring up the Villages Report. Click on it again or press ESC to close it.
~
133, 6, 190, 24
Economy Report
Click on this scroll or press F3 to bring up the Economy Report. Click on it again or press ESC to close it.
~
194, 6, 253, 23
Trade Report
Click on this scroll or press F4 to bring up the Trade Report. Click on it again or press ESC to close it.
~
12, 27, 72, 44
Military Report
Click on this scroll or press F5 to bring up the Military Report. Click on it again or press ESC to close it.
~
73, 27, 134, 46
Technology Report
Click on this scroll or press F6 to bring up the Technology Report. Click on it again or press ESC to close it.
~
136, 29, 196, 45
Espionage Report
Click on this scroll or press F7 to bring up the Espionage Report. Click on it again or press ESC to close it.
~
198, 28, 259, 45
Ranking Report
Click on this scroll or press F8 to bring up the Ranking Report. Click on it again or press ESC to close it.
~
266, 6, 440, 25
Food
This shows the store of food in your kingdom.
~
266, 26, 440, 47
Treasure
This shows the amount of treasure in your kingdom.
~
460, 6, 564, 25
Date
This shows the current Date.
~
447, 25, 540, 47
Reputation
This shows your kingdom's reputation.
~
587, 8, 625, 45
Terrain Map
This map shows the world's natural features and the location of villages and units.
~
629, 8, 668, 45
Kingdom Power Map
This map shows the political boundaries of every kingdom and the location of villages and units.
~
673, 8, 710, 45
Villages and Units Map
This map shows the location of villages and units.
~
BRIBE
Offer Bribe
Make a bribe with the selected spy. This takes you to a menu where you can choose the amount of the bribe to offer to the selected foreign unit.
~
BUILD
Build
This enables you to choose a structure to build. If you do not have enough money to build a structure, this tile is disabled.
~
CANCEL
Cancel
This cancels your present action.
~
CAPTURE
Capture
This captures the selected structure for your kingdom.
~
CHGPROD
Change Production
This toggles production in this factory between iron, copper, and clay products.
~
COLLTAX
Collect Tax
This collects tax from the selected village. If you right-click, you will be able to set a maximum loyalty level to tax your villagers automatically.
~
CONTINUE
Continue
~
DEFENSE0
At Ease
This orders your troops to remain in the fort even when attacked.
~
DEFENSE1
Alert
This orders your troops to sortie whenever the fort or linked structures are attacked.
~
DEMOTE
Demote Unit
This demotes the selected General to a common soldier.
~
GRANT
Grant
This grants money to the selected village. If you right-click, you will be able to set a loyalty level to grant money automatically.
~
GRANT2
Grant
This grants money to the selected village to lower the villagers' loyalty or resistance.
~
HIRECARA
Hire Caravan
This hires a caravan from this market so that you can conduct trade and move goods. It is disabled if you have too few villagers to support any more caravans. 10 villagers are needed to support each caravan.
~
HIREUNIT
Hire Mercenary
This hires the selected mercenary to be in your service.
~
INVOKE
Invoke Greater Being
This invokes a Greater Being who will then appear over your Seat of Power. This tile is disabled until you have enough praying points to make invocation possible.
~
MAKESHIP
Build a Ship
This takes you to a menu where you can select ships to build in this harbor.
~
MAKEWEAP
Make a Weapon
This takes you to a menu where you can select weapons to make in this war factory.
~
MOBILIZE
Mobilize Workers
This causes all workers to exit the building immediately.
~
MOBILSPY
Mobilize Spy
This sends the selected spy out of the place where he has infiltrated.
~
OUTSHIP
Disembark from Ship
The disembarks all of the units from this ship. This tile is disabled if your ship is not close enough to the shore.
~
PATROL
Sortie
This sorties the troop from this fort.
~
RETCAMP
Withdraw
This immediately withdraws your troop to its home fort.
~
PREVMENU
Previous Menu
This returns you to the previous menu.
~
PROMOTE
Promote
This promotes the selected common soldier to a General.
~
RECRUIT
Recruit
This recruits a peasant from the selected village. For each click, one peasant exits. This tile is disabled if there are no more peasants in the village.
~
RESEARCH
Conduct Research
This orders the start of a research project. This is disabled if all possible research has been completed.
~
REWARD
Honors
This awards an honor to the selected unit. For each honor, the unit's loyalty increases by 10 points. This is disabled for the King.
~
REWARDCB
Honors
This awards an honor to the selected General or soldier in this fort. For each honor, the unit's loyalty increases by 10 points. This is disabled for the King.
~
REWARDSP
Honors
This awards an honor to the selected General or prayer in this Seat of Power. For each honor, the unit's loyalty increases by 10 points. This is disabled for the King.
~
SAILOUT
Sail out of Harbor
This orders the selected ship to sail out of the harbor and await your further commands.
~
SELBRIBE
Offer Bribe
This takes you to a menu where you can choose the amount of the bribe to offer to the selected foreign unit. If more than one spy is in the building, you will also be prompted to select one of your spies to do the offer.
~
SETTLE
Settle
This orders the selected people to settle on vacant land or in an established village. If this unit is a spy, this tile can also be used to settle the spy in an enemy's village.
~
SPYMENU
Spy Menu
Go to the spy menu.
~
SPYCAPT
Capture Enemy Structure
This orders the selected spy to capture the enemy structure in which he is located.
~
SPYCHACT
Spy's Task
This orders your spy to change his task.
~
SPYNOTI0
Notification Currently Disabled. Click to Enable.
When this is disabled, it keeps your spy's change of color a secret. You retain the ability to control your spy's movement.
~
SPYNOTI1
Notification Currently Enabled. Click to Disable.
When this is enabled, it announces your spy's change of color to the kingdom that he is joining. You lose your ability to control your spy's movement.
~
SUCCEED
Succeed to the Crown
This elevates the selected unit to the Crown.
~
TRAIN
Train
This trains a villager in a selected skill. This tile is disabled if there are no more peasants in the village or if you do not have a General in a fort linked to the village.
~
VSECRET
View Secrets
This takes you to a menu where you can select the type of this kingdom's secrets to view. The secrets that you can view depend on the skill level of your spy.
~
NOSPY
Drop Spy Identity
This causes the spy to give up his spy identity.
~
AUTOPICK
Automatic
With this set, your caravans and ships will automatically pick up the surplus goods from this market or harbor.
~
NOPICK
Nothing
With this set, your caravans and ships will not pick up anything from this market or harbor.
~
RESIGN
Disband Unit
This disbands the selected unit. If the selected unit is a foreign spy, it executes him.
~
CSETSTOP
Set Caravan Stop
After you press this button, click your cursor on the location where you want your caravan to stop.
~
CGOSTOP
View Caravan Stop
Click here to center the map over this caravan stop.
~
CDELSTOP
Delete Caravan Stop
Click here to delete this caravan stop.
~
SSETSTOP
Set Trade Ship Stop
After you press this button, click your cursor on the harbor where you want your trade ship to stop.
~
SGOSTOP
View Trade Ship Stop
Click here to center the map over this trade ship stop.
~
SDELSTOP
Delete Trade Ship Stop
Click here to delete this trade ship stop.
~
DESTFIRM
Demolish Structure
Click here to demolish this structure.
~
SELLFIRM
Sell Structure
Click here to sell this structure.
~
REPAIR
Structure Repair Icon
This icon shows there is a construction worker stationed in this structure. Click or right-click on this icon to mobilize the construction worker.
~
REPLYDIP
Zoom to Activity
Click on this box to reply to the message or to see the location of the event.
~
NEWSLOG
News Log
Click on this to bring up the news log.
~
CLRNEWS
Clear News Messages
Click on this to clear all news messages on the screen. You can also press X on your keyboard.
~
GAMEMENU
Game Menu
Click on this button to bring up the Game Menu.
~
MK_STOCK
Stock
This shows the current stock of this type of goods in the market.
~
MK_SALES
Sales
This shows the total sales of this type of goods in the market in the past 365 days.
~
MK_DEMAN
Demand
This shows the monthly demand for goods from villages linked to this market.
~
MK_INCOM
Yearly Income
This shows the total income of this market in the past 365 days.
~
MK_CLEAR
Clear Stock
Click on this button to clear all of the stock of this type of goods in the market.
~
FC_PROD
Monthly Production
This shows the quantity of the product manufactured by this factory in the past 30 days.
~
FC_RAW
Raw Material Stock
This shows the current stock of the raw material used for manufacturing in this factory. The maximum capacity for storing the stock in a factory is 500.
~
FC_PROD
Product Stock
This shows the current stock of the finished goods in this factory. The maximum capacity for storing the stock in a factory is 500.
~
CANCELWP
Cancel Weapon Production
Click on this to cancel producing the current weapon.
~
CANCELSHP
Cancel Building Ship
Click on this to cancel building the current ship.
~
CANCELTRA
Cancel Training
Click on this to cancel training the current unit.
~
CANCELBLD
Cancel Building Structure
Click on this to cancel building the current structure.
~
MN_PROD
Monthly Production
This shows the quantity of the product manufactured by this factory in the past 30 days.
~
MN_STOCK
Mined Stock
This shows the amount of material that has already been mined and is being stored at the mine.
~
MN_UNTAP
Untapped Reserve
This shows the amount of natural resources still remaining underground.
~
IMPORT
Yearly Import
This shows the monetary amount of your yearly imports from the selected kingdom.
~
EXPORT
Yearly Export
This shows the monetary amount of your yearly exports to the selected kingdom.
~
STATTIME
Duration of the Current Status
This shows the amount of time that you have been in the current diplomatic status with the selected kingdom.
~
PEACE
Continuous Peace
This shows the amount of time that you have been at peace with the selected kingdom.
~
ALLOWATK
Allow Attack
If this is set to 'Yes', you will be able to target and attack the units and structures of the selected kingdom. If it is set to 'No', you will not.
~
AGGRESS0
Passive Mode Enabled. Click for Aggressive Mode.
When toggled to this mode, your units will not fight unless attacked. If ordered to change location, they will not stop to fight off an attack.
~
AGGRESS1
Aggressive Mode Enabled. Click for Passive Mode.
When toggled to this mode, your units will automatically attack an enemy in their area, but they will not follow it out of the area. If ordered to change location, they will stop to fight off an attack and then continue.
~
ASSASSIN
Assassinate
When you Click on this tile, your selected spy will attempt to assassinate the fort's King or General.
~
GODHEAL
Dispense Healing
When you Click on this tile, your cursor will change into a large white circle. Place this circle over your injured units and Click again. Repeat until the Lord of Healing's power has been depleted.
~
GODMIND
Change Loyalty
When you Click on this tile, your cursor will change into a large white circle. Place this circle over your target and Click again. Repeat until the Mind Turner's power has been depleted.
~
GODINCCL
Increase Power of Maya Soldiers
When you Click on this tile, your cursor will change into a large white circle. Place this circle over your soldiers and Click again. Repeat until Kukulcan's power has been depleted.
~
GODRAIN
Summon Rain
When you Click on this tile, it will cause the rains to come to the whole world. Repeat until Thor's power has been depleted.
~
GODTORNA
Summon Tornadoes
When you Click on this tile, your cursor will change into a small square. Place this square over your target and Click again. Repeat until Thor's power has been depleted.
~
REPAIRQ
Structure Repair Icon
This icon shows there is not a construction worker stationed here for repair but an idle worker may be requested. Click or right-click on this icon to request sending a construction worker.
~
MK_RSTKF
Restocking Source
This shows you which type of linked buildings this market may restock from.
~
MK_RSTKS
Switch Restocking Source
Click this button to change the type of linked buildings this market may restock from. This allows you to control this market's purpose.
