@default_files = ("7kaa.tex"); # compile only 7kaa.tex
$makeindex = "makeindex -s 7kaa.ist 7kaa.idx";
$recorder = 1;
$pdf_mode = 1; # tex -> PDF
$bibtex_use = 2;
$pdflatex = "pdflatex -synctex=1 -shell-escape -interaction=nonstopmode";
$clean_ext = "aux bbl blg fdb_latexmk fls log out"; # delete files with these extensions when latexmk -c
