//Filename	  : OTALKMSG.H
//Description : Header file for class TalkMsg

#ifndef __OTALKMSG_H
#define __OTALKMSG_H

//-------- define talk id. --------//

enum { MAX_TALK_TYPE	= 20 };

enum { TALK_PROPOSE_TRADE_TREATY=1,
		 TALK_PROPOSE_FRIENDLY_TREATY,
		 TALK_PROPOSE_ALLIANCE_TREATY,
		 TALK_END_TRADE_TREATY,
		 TALK_END_FRIENDLY_TREATY,
		 TALK_END_ALLIANCE_TREATY,
		 TALK_REQUEST_MILITARY_AID,
		 TALK_REQUEST_TRADE_EMBARGO,
		 TALK_REQUEST_CEASE_WAR,
		 TALK_REQUEST_DECLARE_WAR,
		 TALK_REQUEST_BUY_FOOD,
		 TALK_DECLARE_WAR,
		 TALK_GIVE_TRIBUTE,
		 TALK_DEMAND_TRIBUTE,
		 TALK_GIVE_AID,
		 TALK_DEMAND_AID,
		 TALK_GIVE_TECH,
		 TALK_DEMAND_TECH,
       TALK_REQUEST_SURRENDER, 
		 TALK_SURRENDER,
	  };

//----------------------------------//

#endif